backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: 'Template Key'
        name: 'templateKey'
        widget: 'hidden'
        default: 'blog'
      - label: 'Title'
        name: 'title'
        widget: 'string'
